// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/scionproto/scion/go/pkg/co/colibri/bootstrap (interfaces: Bootstrapper,ClientCryptoProvider,ExtendedReservationManager,SetReqBuilder,DRKeyProvider,UpSegProvider)

// Package mock_bootstrap is a generated GoMock package.
package mock_bootstrap

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	reservation "github.com/scionproto/scion/go/co/reservation"
	segment "github.com/scionproto/scion/go/co/reservation/segment"
	reservationstorage "github.com/scionproto/scion/go/co/reservationstorage"
	addr "github.com/scionproto/scion/go/lib/addr"
	colibri "github.com/scionproto/scion/go/lib/colibri"
	drkey "github.com/scionproto/scion/go/lib/drkey"
	snet "github.com/scionproto/scion/go/lib/snet"
	bootstrap "github.com/scionproto/scion/go/pkg/co/colibri/bootstrap"
	colibri0 "github.com/scionproto/scion/go/pkg/proto/colibri"
)

// MockBootstrapper is a mock of Bootstrapper interface.
type MockBootstrapper struct {
	ctrl     *gomock.Controller
	recorder *MockBootstrapperMockRecorder
}

// MockBootstrapperMockRecorder is the mock recorder for MockBootstrapper.
type MockBootstrapperMockRecorder struct {
	mock *MockBootstrapper
}

// NewMockBootstrapper creates a new mock instance.
func NewMockBootstrapper(ctrl *gomock.Controller) *MockBootstrapper {
	mock := &MockBootstrapper{ctrl: ctrl}
	mock.recorder = &MockBootstrapperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBootstrapper) EXPECT() *MockBootstrapperMockRecorder {
	return m.recorder
}

// SendDRKeyReq mocks base method.
func (m *MockBootstrapper) SendDRKeyReq(arg0 context.Context, arg1 *colibri.FullTrip, arg2 time.Time) (*drkey.Lvl2Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendDRKeyReq", arg0, arg1, arg2)
	ret0, _ := ret[0].(*drkey.Lvl2Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendDRKeyReq indicates an expected call of SendDRKeyReq.
func (mr *MockBootstrapperMockRecorder) SendDRKeyReq(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendDRKeyReq", reflect.TypeOf((*MockBootstrapper)(nil).SendDRKeyReq), arg0, arg1, arg2)
}

// TelescopeUpstream mocks base method.
func (m *MockBootstrapper) TelescopeUpstream(arg0 context.Context, arg1 []addr.IA) (*colibri.ReservationLooks, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TelescopeUpstream", arg0, arg1)
	ret0, _ := ret[0].(*colibri.ReservationLooks)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TelescopeUpstream indicates an expected call of TelescopeUpstream.
func (mr *MockBootstrapperMockRecorder) TelescopeUpstream(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TelescopeUpstream", reflect.TypeOf((*MockBootstrapper)(nil).TelescopeUpstream), arg0, arg1)
}

// MockClientCryptoProvider is a mock of ClientCryptoProvider interface.
type MockClientCryptoProvider struct {
	ctrl     *gomock.Controller
	recorder *MockClientCryptoProviderMockRecorder
}

// MockClientCryptoProviderMockRecorder is the mock recorder for MockClientCryptoProvider.
type MockClientCryptoProviderMockRecorder struct {
	mock *MockClientCryptoProvider
}

// NewMockClientCryptoProvider creates a new mock instance.
func NewMockClientCryptoProvider(ctrl *gomock.Controller) *MockClientCryptoProvider {
	mock := &MockClientCryptoProvider{ctrl: ctrl}
	mock.recorder = &MockClientCryptoProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientCryptoProvider) EXPECT() *MockClientCryptoProviderMockRecorder {
	return m.recorder
}

// GenerateKeyPair mocks base method.
func (m *MockClientCryptoProvider) GenerateKeyPair() ([]byte, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateKeyPair")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GenerateKeyPair indicates an expected call of GenerateKeyPair.
func (mr *MockClientCryptoProviderMockRecorder) GenerateKeyPair() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateKeyPair", reflect.TypeOf((*MockClientCryptoProvider)(nil).GenerateKeyPair))
}

// Sign mocks base method.
func (m *MockClientCryptoProvider) Sign(arg0 context.Context, arg1 bootstrap.DRKeyReq) (*colibri0.DRKeyRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sign", arg0, arg1)
	ret0, _ := ret[0].(*colibri0.DRKeyRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sign indicates an expected call of Sign.
func (mr *MockClientCryptoProviderMockRecorder) Sign(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sign", reflect.TypeOf((*MockClientCryptoProvider)(nil).Sign), arg0, arg1)
}

// VerifyDecrypt mocks base method.
func (m *MockClientCryptoProvider) VerifyDecrypt(arg0 context.Context, arg1 []byte, arg2 addr.IA, arg3 *colibri0.DRKeyResponse) (*drkey.Lvl2Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyDecrypt", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*drkey.Lvl2Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyDecrypt indicates an expected call of VerifyDecrypt.
func (mr *MockClientCryptoProviderMockRecorder) VerifyDecrypt(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyDecrypt", reflect.TypeOf((*MockClientCryptoProvider)(nil).VerifyDecrypt), arg0, arg1, arg2, arg3)
}

// MockExtendedReservationManager is a mock of ExtendedReservationManager interface.
type MockExtendedReservationManager struct {
	ctrl     *gomock.Controller
	recorder *MockExtendedReservationManagerMockRecorder
}

// MockExtendedReservationManagerMockRecorder is the mock recorder for MockExtendedReservationManager.
type MockExtendedReservationManagerMockRecorder struct {
	mock *MockExtendedReservationManager
}

// NewMockExtendedReservationManager creates a new mock instance.
func NewMockExtendedReservationManager(ctrl *gomock.Controller) *MockExtendedReservationManager {
	mock := &MockExtendedReservationManager{ctrl: ctrl}
	mock.recorder = &MockExtendedReservationManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExtendedReservationManager) EXPECT() *MockExtendedReservationManagerMockRecorder {
	return m.recorder
}

// ActivateManyRequest mocks base method.
func (m *MockExtendedReservationManager) ActivateManyRequest(arg0 context.Context, arg1 []*reservation.Request) []error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateManyRequest", arg0, arg1)
	ret0, _ := ret[0].([]error)
	return ret0
}

// ActivateManyRequest indicates an expected call of ActivateManyRequest.
func (mr *MockExtendedReservationManagerMockRecorder) ActivateManyRequest(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateManyRequest", reflect.TypeOf((*MockExtendedReservationManager)(nil).ActivateManyRequest), arg0, arg1)
}

// ActivateRequest mocks base method.
func (m *MockExtendedReservationManager) ActivateRequest(arg0 context.Context, arg1 *reservation.Request) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateRequest", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ActivateRequest indicates an expected call of ActivateRequest.
func (mr *MockExtendedReservationManagerMockRecorder) ActivateRequest(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateRequest", reflect.TypeOf((*MockExtendedReservationManager)(nil).ActivateRequest), arg0, arg1)
}

// DRKey mocks base method.
func (m *MockExtendedReservationManager) DRKey(arg0 context.Context, arg1 *colibri0.DRKeyRequest) (*colibri0.DRKeyResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DRKey", arg0, arg1)
	ret0, _ := ret[0].(*colibri0.DRKeyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DRKey indicates an expected call of DRKey.
func (mr *MockExtendedReservationManagerMockRecorder) DRKey(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DRKey", reflect.TypeOf((*MockExtendedReservationManager)(nil).DRKey), arg0, arg1)
}

// GetDRKey mocks base method.
func (m *MockExtendedReservationManager) GetDRKey(arg0 context.Context, arg1 drkey.Lvl2Meta, arg2 time.Time) (*drkey.Lvl2Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDRKey", arg0, arg1, arg2)
	ret0, _ := ret[0].(*drkey.Lvl2Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDRKey indicates an expected call of GetDRKey.
func (mr *MockExtendedReservationManagerMockRecorder) GetDRKey(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDRKey", reflect.TypeOf((*MockExtendedReservationManager)(nil).GetDRKey), arg0, arg1, arg2)
}

// LocalIA mocks base method.
func (m *MockExtendedReservationManager) LocalIA() addr.IA {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LocalIA")
	ret0, _ := ret[0].(addr.IA)
	return ret0
}

// LocalIA indicates an expected call of LocalIA.
func (mr *MockExtendedReservationManagerMockRecorder) LocalIA() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LocalIA", reflect.TypeOf((*MockExtendedReservationManager)(nil).LocalIA))
}

// LookupNR mocks base method.
func (m *MockExtendedReservationManager) LookupNR(arg0 context.Context, arg1, arg2 addr.IA) (*colibri.ReservationLooks, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookupNR", arg0, arg1, arg2)
	ret0, _ := ret[0].(*colibri.ReservationLooks)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookupNR indicates an expected call of LookupNR.
func (mr *MockExtendedReservationManagerMockRecorder) LookupNR(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookupNR", reflect.TypeOf((*MockExtendedReservationManager)(nil).LookupNR), arg0, arg1, arg2)
}

// Name mocks base method.
func (m *MockExtendedReservationManager) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockExtendedReservationManagerMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockExtendedReservationManager)(nil).Name))
}

// Now mocks base method.
func (m *MockExtendedReservationManager) Now() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Now")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now.
func (mr *MockExtendedReservationManagerMockRecorder) Now() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Now", reflect.TypeOf((*MockExtendedReservationManager)(nil).Now))
}

// PathsTo mocks base method.
func (m *MockExtendedReservationManager) PathsTo(arg0 context.Context, arg1 addr.IA) ([]snet.Path, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PathsTo", arg0, arg1)
	ret0, _ := ret[0].([]snet.Path)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PathsTo indicates an expected call of PathsTo.
func (mr *MockExtendedReservationManagerMockRecorder) PathsTo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PathsTo", reflect.TypeOf((*MockExtendedReservationManager)(nil).PathsTo), arg0, arg1)
}

// Run mocks base method.
func (m *MockExtendedReservationManager) Run(arg0 context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Run", arg0)
}

// Run indicates an expected call of Run.
func (mr *MockExtendedReservationManagerMockRecorder) Run(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockExtendedReservationManager)(nil).Run), arg0)
}

// SetupManyRequest mocks base method.
func (m *MockExtendedReservationManager) SetupManyRequest(arg0 context.Context, arg1 []*segment.SetupReq) []error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetupManyRequest", arg0, arg1)
	ret0, _ := ret[0].([]error)
	return ret0
}

// SetupManyRequest indicates an expected call of SetupManyRequest.
func (mr *MockExtendedReservationManagerMockRecorder) SetupManyRequest(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetupManyRequest", reflect.TypeOf((*MockExtendedReservationManager)(nil).SetupManyRequest), arg0, arg1)
}

// SetupRequest mocks base method.
func (m *MockExtendedReservationManager) SetupRequest(arg0 context.Context, arg1 *segment.SetupReq) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetupRequest", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetupRequest indicates an expected call of SetupRequest.
func (mr *MockExtendedReservationManagerMockRecorder) SetupRequest(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetupRequest", reflect.TypeOf((*MockExtendedReservationManager)(nil).SetupRequest), arg0, arg1)
}

// Store mocks base method.
func (m *MockExtendedReservationManager) Store() reservationstorage.Store {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store")
	ret0, _ := ret[0].(reservationstorage.Store)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockExtendedReservationManagerMockRecorder) Store() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockExtendedReservationManager)(nil).Store))
}

// StoreDRkey mocks base method.
func (m *MockExtendedReservationManager) StoreDRkey(arg0 context.Context, arg1 *drkey.Lvl2Key) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreDRkey", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreDRkey indicates an expected call of StoreDRkey.
func (mr *MockExtendedReservationManagerMockRecorder) StoreDRkey(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreDRkey", reflect.TypeOf((*MockExtendedReservationManager)(nil).StoreDRkey), arg0, arg1)
}

// MockSetReqBuilder is a mock of SetReqBuilder interface.
type MockSetReqBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockSetReqBuilderMockRecorder
}

// MockSetReqBuilderMockRecorder is the mock recorder for MockSetReqBuilder.
type MockSetReqBuilderMockRecorder struct {
	mock *MockSetReqBuilder
}

// NewMockSetReqBuilder creates a new mock instance.
func NewMockSetReqBuilder(ctrl *gomock.Controller) *MockSetReqBuilder {
	mock := &MockSetReqBuilder{ctrl: ctrl}
	mock.recorder = &MockSetReqBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSetReqBuilder) EXPECT() *MockSetReqBuilderMockRecorder {
	return m.recorder
}

// BuildSetReq mocks base method.
func (m *MockSetReqBuilder) BuildSetReq(arg0 context.Context, arg1 colibri.FullTrip, arg2 addr.IA) (*segment.SetupReq, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildSetReq", arg0, arg1, arg2)
	ret0, _ := ret[0].(*segment.SetupReq)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildSetReq indicates an expected call of BuildSetReq.
func (mr *MockSetReqBuilderMockRecorder) BuildSetReq(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildSetReq", reflect.TypeOf((*MockSetReqBuilder)(nil).BuildSetReq), arg0, arg1, arg2)
}

// MockDRKeyProvider is a mock of DRKeyProvider interface.
type MockDRKeyProvider struct {
	ctrl     *gomock.Controller
	recorder *MockDRKeyProviderMockRecorder
}

// MockDRKeyProviderMockRecorder is the mock recorder for MockDRKeyProvider.
type MockDRKeyProviderMockRecorder struct {
	mock *MockDRKeyProvider
}

// NewMockDRKeyProvider creates a new mock instance.
func NewMockDRKeyProvider(ctrl *gomock.Controller) *MockDRKeyProvider {
	mock := &MockDRKeyProvider{ctrl: ctrl}
	mock.recorder = &MockDRKeyProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDRKeyProvider) EXPECT() *MockDRKeyProviderMockRecorder {
	return m.recorder
}

// GetKey mocks base method.
func (m *MockDRKeyProvider) GetKey(arg0 context.Context, arg1 drkey.Lvl2Meta, arg2 time.Time) (*drkey.Lvl2Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKey", arg0, arg1, arg2)
	ret0, _ := ret[0].(*drkey.Lvl2Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKey indicates an expected call of GetKey.
func (mr *MockDRKeyProviderMockRecorder) GetKey(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKey", reflect.TypeOf((*MockDRKeyProvider)(nil).GetKey), arg0, arg1, arg2)
}

// MockUpSegProvider is a mock of UpSegProvider interface.
type MockUpSegProvider struct {
	ctrl     *gomock.Controller
	recorder *MockUpSegProviderMockRecorder
}

// MockUpSegProviderMockRecorder is the mock recorder for MockUpSegProvider.
type MockUpSegProviderMockRecorder struct {
	mock *MockUpSegProvider
}

// NewMockUpSegProvider creates a new mock instance.
func NewMockUpSegProvider(ctrl *gomock.Controller) *MockUpSegProvider {
	mock := &MockUpSegProvider{ctrl: ctrl}
	mock.recorder = &MockUpSegProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpSegProvider) EXPECT() *MockUpSegProviderMockRecorder {
	return m.recorder
}

// UpSegIAs mocks base method.
func (m *MockUpSegProvider) UpSegIAs(arg0 context.Context, arg1 addr.IA) ([][]addr.IA, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpSegIAs", arg0, arg1)
	ret0, _ := ret[0].([][]addr.IA)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpSegIAs indicates an expected call of UpSegIAs.
func (mr *MockUpSegProviderMockRecorder) UpSegIAs(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpSegIAs", reflect.TypeOf((*MockUpSegProvider)(nil).UpSegIAs), arg0, arg1)
}
