// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/scionproto/scion/go/pkg/co/colibri/bootstrap (interfaces: AsymClientProvider,ExtendedReservationManager,SetReqBuilder,DRKeyProvider)

// Package mock_bootstrap is a generated GoMock package.
package mock_bootstrap

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	reservation "github.com/scionproto/scion/go/co/reservation"
	segment "github.com/scionproto/scion/go/co/reservation/segment"
	reservationstorage "github.com/scionproto/scion/go/co/reservationstorage"
	addr "github.com/scionproto/scion/go/lib/addr"
	colibri "github.com/scionproto/scion/go/lib/colibri"
	drkey "github.com/scionproto/scion/go/lib/drkey"
	snet "github.com/scionproto/scion/go/lib/snet"
	bootstrap "github.com/scionproto/scion/go/pkg/co/colibri/bootstrap"
	crypto "github.com/scionproto/scion/go/pkg/proto/crypto"
)

// MockAsymClientProvider is a mock of AsymClientProvider interface.
type MockAsymClientProvider struct {
	ctrl     *gomock.Controller
	recorder *MockAsymClientProviderMockRecorder
}

// MockAsymClientProviderMockRecorder is the mock recorder for MockAsymClientProvider.
type MockAsymClientProviderMockRecorder struct {
	mock *MockAsymClientProvider
}

// NewMockAsymClientProvider creates a new mock instance.
func NewMockAsymClientProvider(ctrl *gomock.Controller) *MockAsymClientProvider {
	mock := &MockAsymClientProvider{ctrl: ctrl}
	mock.recorder = &MockAsymClientProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAsymClientProvider) EXPECT() *MockAsymClientProviderMockRecorder {
	return m.recorder
}

// GenerateKeyPair mocks base method.
func (m *MockAsymClientProvider) GenerateKeyPair() ([]byte, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateKeyPair")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GenerateKeyPair indicates an expected call of GenerateKeyPair.
func (mr *MockAsymClientProviderMockRecorder) GenerateKeyPair() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateKeyPair", reflect.TypeOf((*MockAsymClientProvider)(nil).GenerateKeyPair))
}

// Sign mocks base method.
func (m *MockAsymClientProvider) Sign(arg0 context.Context, arg1 bootstrap.Lvl1Req) (*crypto.SignedMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sign", arg0, arg1)
	ret0, _ := ret[0].(*crypto.SignedMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sign indicates an expected call of Sign.
func (mr *MockAsymClientProviderMockRecorder) Sign(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sign", reflect.TypeOf((*MockAsymClientProvider)(nil).Sign), arg0, arg1)
}

// VerifyAndDecrypt mocks base method.
func (m *MockAsymClientProvider) VerifyAndDecrypt(arg0 context.Context, arg1 addr.IA, arg2 []byte, arg3 *crypto.SignedMessage, arg4 ...[]byte) (*drkey.Lvl1Key, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2, arg3}
	for _, a := range arg4 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "VerifyAndDecrypt", varargs...)
	ret0, _ := ret[0].(*drkey.Lvl1Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyAndDecrypt indicates an expected call of VerifyAndDecrypt.
func (mr *MockAsymClientProviderMockRecorder) VerifyAndDecrypt(arg0, arg1, arg2, arg3 interface{}, arg4 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2, arg3}, arg4...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyAndDecrypt", reflect.TypeOf((*MockAsymClientProvider)(nil).VerifyAndDecrypt), varargs...)
}

// MockExtendedReservationManager is a mock of ExtendedReservationManager interface.
type MockExtendedReservationManager struct {
	ctrl     *gomock.Controller
	recorder *MockExtendedReservationManagerMockRecorder
}

// MockExtendedReservationManagerMockRecorder is the mock recorder for MockExtendedReservationManager.
type MockExtendedReservationManagerMockRecorder struct {
	mock *MockExtendedReservationManager
}

// NewMockExtendedReservationManager creates a new mock instance.
func NewMockExtendedReservationManager(ctrl *gomock.Controller) *MockExtendedReservationManager {
	mock := &MockExtendedReservationManager{ctrl: ctrl}
	mock.recorder = &MockExtendedReservationManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExtendedReservationManager) EXPECT() *MockExtendedReservationManagerMockRecorder {
	return m.recorder
}

// ActivateManyRequest mocks base method.
func (m *MockExtendedReservationManager) ActivateManyRequest(arg0 context.Context, arg1 []*reservation.Request) []error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateManyRequest", arg0, arg1)
	ret0, _ := ret[0].([]error)
	return ret0
}

// ActivateManyRequest indicates an expected call of ActivateManyRequest.
func (mr *MockExtendedReservationManagerMockRecorder) ActivateManyRequest(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateManyRequest", reflect.TypeOf((*MockExtendedReservationManager)(nil).ActivateManyRequest), arg0, arg1)
}

// ActivateRequest mocks base method.
func (m *MockExtendedReservationManager) ActivateRequest(arg0 context.Context, arg1 *reservation.Request) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateRequest", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ActivateRequest indicates an expected call of ActivateRequest.
func (mr *MockExtendedReservationManagerMockRecorder) ActivateRequest(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateRequest", reflect.TypeOf((*MockExtendedReservationManager)(nil).ActivateRequest), arg0, arg1)
}

// GetLvl1 mocks base method.
func (m *MockExtendedReservationManager) GetLvl1(arg0 context.Context, arg1 drkey.Lvl1Meta, arg2 time.Time) (*drkey.Lvl1Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLvl1", arg0, arg1, arg2)
	ret0, _ := ret[0].(*drkey.Lvl1Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLvl1 indicates an expected call of GetLvl1.
func (mr *MockExtendedReservationManagerMockRecorder) GetLvl1(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLvl1", reflect.TypeOf((*MockExtendedReservationManager)(nil).GetLvl1), arg0, arg1, arg2)
}

// LocalIA mocks base method.
func (m *MockExtendedReservationManager) LocalIA() addr.IA {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LocalIA")
	ret0, _ := ret[0].(addr.IA)
	return ret0
}

// LocalIA indicates an expected call of LocalIA.
func (mr *MockExtendedReservationManagerMockRecorder) LocalIA() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LocalIA", reflect.TypeOf((*MockExtendedReservationManager)(nil).LocalIA))
}

// LookupNR mocks base method.
func (m *MockExtendedReservationManager) LookupNR(arg0 context.Context, arg1, arg2 addr.IA) (*colibri.ReservationLooks, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookupNR", arg0, arg1, arg2)
	ret0, _ := ret[0].(*colibri.ReservationLooks)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookupNR indicates an expected call of LookupNR.
func (mr *MockExtendedReservationManagerMockRecorder) LookupNR(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookupNR", reflect.TypeOf((*MockExtendedReservationManager)(nil).LookupNR), arg0, arg1, arg2)
}

// Lvl1 mocks base method.
func (m *MockExtendedReservationManager) Lvl1(arg0 context.Context, arg1 *crypto.SignedMessage) (*crypto.SignedMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lvl1", arg0, arg1)
	ret0, _ := ret[0].(*crypto.SignedMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Lvl1 indicates an expected call of Lvl1.
func (mr *MockExtendedReservationManagerMockRecorder) Lvl1(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lvl1", reflect.TypeOf((*MockExtendedReservationManager)(nil).Lvl1), arg0, arg1)
}

// Name mocks base method.
func (m *MockExtendedReservationManager) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockExtendedReservationManagerMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockExtendedReservationManager)(nil).Name))
}

// Now mocks base method.
func (m *MockExtendedReservationManager) Now() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Now")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now.
func (mr *MockExtendedReservationManagerMockRecorder) Now() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Now", reflect.TypeOf((*MockExtendedReservationManager)(nil).Now))
}

// PathsTo mocks base method.
func (m *MockExtendedReservationManager) PathsTo(arg0 context.Context, arg1 addr.IA) ([]snet.Path, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PathsTo", arg0, arg1)
	ret0, _ := ret[0].([]snet.Path)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PathsTo indicates an expected call of PathsTo.
func (mr *MockExtendedReservationManagerMockRecorder) PathsTo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PathsTo", reflect.TypeOf((*MockExtendedReservationManager)(nil).PathsTo), arg0, arg1)
}

// Run mocks base method.
func (m *MockExtendedReservationManager) Run(arg0 context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Run", arg0)
}

// Run indicates an expected call of Run.
func (mr *MockExtendedReservationManagerMockRecorder) Run(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockExtendedReservationManager)(nil).Run), arg0)
}

// SetupManyRequest mocks base method.
func (m *MockExtendedReservationManager) SetupManyRequest(arg0 context.Context, arg1 []*segment.SetupReq) []error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetupManyRequest", arg0, arg1)
	ret0, _ := ret[0].([]error)
	return ret0
}

// SetupManyRequest indicates an expected call of SetupManyRequest.
func (mr *MockExtendedReservationManagerMockRecorder) SetupManyRequest(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetupManyRequest", reflect.TypeOf((*MockExtendedReservationManager)(nil).SetupManyRequest), arg0, arg1)
}

// SetupRequest mocks base method.
func (m *MockExtendedReservationManager) SetupRequest(arg0 context.Context, arg1 *segment.SetupReq) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetupRequest", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetupRequest indicates an expected call of SetupRequest.
func (mr *MockExtendedReservationManagerMockRecorder) SetupRequest(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetupRequest", reflect.TypeOf((*MockExtendedReservationManager)(nil).SetupRequest), arg0, arg1)
}

// Store mocks base method.
func (m *MockExtendedReservationManager) Store() reservationstorage.Store {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store")
	ret0, _ := ret[0].(reservationstorage.Store)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockExtendedReservationManagerMockRecorder) Store() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockExtendedReservationManager)(nil).Store))
}

// StoreLvl1 mocks base method.
func (m *MockExtendedReservationManager) StoreLvl1(arg0 context.Context, arg1 *drkey.Lvl1Key) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreLvl1", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreLvl1 indicates an expected call of StoreLvl1.
func (mr *MockExtendedReservationManagerMockRecorder) StoreLvl1(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreLvl1", reflect.TypeOf((*MockExtendedReservationManager)(nil).StoreLvl1), arg0, arg1)
}

// MockSetReqBuilder is a mock of SetReqBuilder interface.
type MockSetReqBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockSetReqBuilderMockRecorder
}

// MockSetReqBuilderMockRecorder is the mock recorder for MockSetReqBuilder.
type MockSetReqBuilderMockRecorder struct {
	mock *MockSetReqBuilder
}

// NewMockSetReqBuilder creates a new mock instance.
func NewMockSetReqBuilder(ctrl *gomock.Controller) *MockSetReqBuilder {
	mock := &MockSetReqBuilder{ctrl: ctrl}
	mock.recorder = &MockSetReqBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSetReqBuilder) EXPECT() *MockSetReqBuilderMockRecorder {
	return m.recorder
}

// BuildSetReq mocks base method.
func (m *MockSetReqBuilder) BuildSetReq(arg0 context.Context, arg1 colibri.FullTrip, arg2 addr.IA) (*segment.SetupReq, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildSetReq", arg0, arg1, arg2)
	ret0, _ := ret[0].(*segment.SetupReq)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildSetReq indicates an expected call of BuildSetReq.
func (mr *MockSetReqBuilderMockRecorder) BuildSetReq(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildSetReq", reflect.TypeOf((*MockSetReqBuilder)(nil).BuildSetReq), arg0, arg1, arg2)
}

// MockDRKeyProvider is a mock of DRKeyProvider interface.
type MockDRKeyProvider struct {
	ctrl     *gomock.Controller
	recorder *MockDRKeyProviderMockRecorder
}

// MockDRKeyProviderMockRecorder is the mock recorder for MockDRKeyProvider.
type MockDRKeyProviderMockRecorder struct {
	mock *MockDRKeyProvider
}

// NewMockDRKeyProvider creates a new mock instance.
func NewMockDRKeyProvider(ctrl *gomock.Controller) *MockDRKeyProvider {
	mock := &MockDRKeyProvider{ctrl: ctrl}
	mock.recorder = &MockDRKeyProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDRKeyProvider) EXPECT() *MockDRKeyProviderMockRecorder {
	return m.recorder
}

// GetLvl1 mocks base method.
func (m *MockDRKeyProvider) GetLvl1(arg0 context.Context, arg1 drkey.Lvl1Meta, arg2 time.Time) (*drkey.Lvl1Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLvl1", arg0, arg1, arg2)
	ret0, _ := ret[0].(*drkey.Lvl1Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLvl1 indicates an expected call of GetLvl1.
func (mr *MockDRKeyProviderMockRecorder) GetLvl1(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLvl1", reflect.TypeOf((*MockDRKeyProvider)(nil).GetLvl1), arg0, arg1, arg2)
}
