// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/scionproto/scion/go/pkg/co/colibri/bootstrap (interfaces: ColibriProvider)

// Package mock_bootstrap is a generated GoMock package.
package mock_bootstrap

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	addr "github.com/scionproto/scion/go/lib/addr"
	colibri "github.com/scionproto/scion/go/lib/colibri"
	drkey "github.com/scionproto/scion/go/lib/drkey"
)

// MockColibriProvider is a mock of ColibriProvider interface.
type MockColibriProvider struct {
	ctrl     *gomock.Controller
	recorder *MockColibriProviderMockRecorder
}

// MockColibriProviderMockRecorder is the mock recorder for MockColibriProvider.
type MockColibriProviderMockRecorder struct {
	mock *MockColibriProvider
}

// NewMockColibriProvider creates a new mock instance.
func NewMockColibriProvider(ctrl *gomock.Controller) *MockColibriProvider {
	mock := &MockColibriProvider{ctrl: ctrl}
	mock.recorder = &MockColibriProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockColibriProvider) EXPECT() *MockColibriProviderMockRecorder {
	return m.recorder
}

// BootstrapLvl1Key mocks base method.
func (m *MockColibriProvider) BootstrapLvl1Key(arg0 context.Context, arg1 colibri.FullTrip) (*drkey.Lvl1Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BootstrapLvl1Key", arg0, arg1)
	ret0, _ := ret[0].(*drkey.Lvl1Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BootstrapLvl1Key indicates an expected call of BootstrapLvl1Key.
func (mr *MockColibriProviderMockRecorder) BootstrapLvl1Key(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BootstrapLvl1Key", reflect.TypeOf((*MockColibriProvider)(nil).BootstrapLvl1Key), arg0, arg1)
}

// GetLvl1 mocks base method.
func (m *MockColibriProvider) GetLvl1(arg0 context.Context, arg1 drkey.Lvl1Meta, arg2 uint32) (*drkey.Lvl1Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLvl1", arg0, arg1, arg2)
	ret0, _ := ret[0].(*drkey.Lvl1Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLvl1 indicates an expected call of GetLvl1.
func (mr *MockColibriProviderMockRecorder) GetLvl1(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLvl1", reflect.TypeOf((*MockColibriProvider)(nil).GetLvl1), arg0, arg1, arg2)
}

// LookupNR mocks base method.
func (m *MockColibriProvider) LookupNR(arg0 context.Context, arg1, arg2 addr.IA) (*colibri.ReservationLooks, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookupNR", arg0, arg1, arg2)
	ret0, _ := ret[0].(*colibri.ReservationLooks)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookupNR indicates an expected call of LookupNR.
func (mr *MockColibriProviderMockRecorder) LookupNR(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookupNR", reflect.TypeOf((*MockColibriProvider)(nil).LookupNR), arg0, arg1, arg2)
}

// SetupUpSegR mocks base method.
func (m *MockColibriProvider) SetupUpSegR(arg0 context.Context, arg1 colibri.FullTrip, arg2 addr.IA) (*colibri.ReservationLooks, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetupUpSegR", arg0, arg1, arg2)
	ret0, _ := ret[0].(*colibri.ReservationLooks)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetupUpSegR indicates an expected call of SetupUpSegR.
func (mr *MockColibriProviderMockRecorder) SetupUpSegR(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetupUpSegR", reflect.TypeOf((*MockColibriProvider)(nil).SetupUpSegR), arg0, arg1, arg2)
}

// StoreLvl1 mocks base method.
func (m *MockColibriProvider) StoreLvl1(arg0 context.Context, arg1 *drkey.Lvl1Key) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreLvl1", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreLvl1 indicates an expected call of StoreLvl1.
func (mr *MockColibriProviderMockRecorder) StoreLvl1(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreLvl1", reflect.TypeOf((*MockColibriProvider)(nil).StoreLvl1), arg0, arg1)
}

// TearDownSeg mocks base method.
func (m *MockColibriProvider) TearDownSeg(arg0 context.Context, arg1 *colibri.ReservationLooks) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TearDownSeg", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// TearDownSeg indicates an expected call of TearDownSeg.
func (mr *MockColibriProviderMockRecorder) TearDownSeg(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TearDownSeg", reflect.TypeOf((*MockColibriProvider)(nil).TearDownSeg), arg0, arg1)
}
