// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/scionproto/scion/go/pkg/grpc (interfaces: Dialer,ServiceResolver)

// Package mock_grpc is a generated GoMock package.
package mock_grpc

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	snet "github.com/scionproto/scion/go/lib/snet"
	grpc "google.golang.org/grpc"
	net "net"
	reflect "reflect"
)

// MockDialer is a mock of Dialer interface
type MockDialer struct {
	ctrl     *gomock.Controller
	recorder *MockDialerMockRecorder
}

// MockDialerMockRecorder is the mock recorder for MockDialer
type MockDialerMockRecorder struct {
	mock *MockDialer
}

// NewMockDialer creates a new mock instance
func NewMockDialer(ctrl *gomock.Controller) *MockDialer {
	mock := &MockDialer{ctrl: ctrl}
	mock.recorder = &MockDialerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDialer) EXPECT() *MockDialerMockRecorder {
	return m.recorder
}

// Dial mocks base method
func (m *MockDialer) Dial(arg0 context.Context, arg1 net.Addr) (*grpc.ClientConn, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dial", arg0, arg1)
	ret0, _ := ret[0].(*grpc.ClientConn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Dial indicates an expected call of Dial
func (mr *MockDialerMockRecorder) Dial(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dial", reflect.TypeOf((*MockDialer)(nil).Dial), arg0, arg1)
}

// MockServiceResolver is a mock of ServiceResolver interface
type MockServiceResolver struct {
	ctrl     *gomock.Controller
	recorder *MockServiceResolverMockRecorder
}

// MockServiceResolverMockRecorder is the mock recorder for MockServiceResolver
type MockServiceResolverMockRecorder struct {
	mock *MockServiceResolver
}

// NewMockServiceResolver creates a new mock instance
func NewMockServiceResolver(ctrl *gomock.Controller) *MockServiceResolver {
	mock := &MockServiceResolver{ctrl: ctrl}
	mock.recorder = &MockServiceResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockServiceResolver) EXPECT() *MockServiceResolverMockRecorder {
	return m.recorder
}

// ResolveChainRenewalService mocks base method
func (m *MockServiceResolver) ResolveChainRenewalService(arg0 context.Context, arg1 *snet.SVCAddr) (*snet.UDPAddr, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveChainRenewalService", arg0, arg1)
	ret0, _ := ret[0].(*snet.UDPAddr)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveChainRenewalService indicates an expected call of ResolveChainRenewalService
func (mr *MockServiceResolverMockRecorder) ResolveChainRenewalService(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveChainRenewalService", reflect.TypeOf((*MockServiceResolver)(nil).ResolveChainRenewalService), arg0, arg1)
}

// ResolveDRKeyService mocks base method
func (m *MockServiceResolver) ResolveDRKeyService(arg0 context.Context, arg1 *snet.SVCAddr) (*snet.UDPAddr, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveDRKeyService", arg0, arg1)
	ret0, _ := ret[0].(*snet.UDPAddr)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveDRKeyService indicates an expected call of ResolveDRKeyService
func (mr *MockServiceResolverMockRecorder) ResolveDRKeyService(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveDRKeyService", reflect.TypeOf((*MockServiceResolver)(nil).ResolveDRKeyService), arg0, arg1)
}

// ResolveSegmentLookupService mocks base method
func (m *MockServiceResolver) ResolveSegmentLookupService(arg0 context.Context, arg1 *snet.SVCAddr) (*snet.UDPAddr, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveSegmentLookupService", arg0, arg1)
	ret0, _ := ret[0].(*snet.UDPAddr)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveSegmentLookupService indicates an expected call of ResolveSegmentLookupService
func (mr *MockServiceResolverMockRecorder) ResolveSegmentLookupService(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveSegmentLookupService", reflect.TypeOf((*MockServiceResolver)(nil).ResolveSegmentLookupService), arg0, arg1)
}

// ResolveSegmentRegService mocks base method
func (m *MockServiceResolver) ResolveSegmentRegService(arg0 context.Context, arg1 *snet.SVCAddr) (*snet.UDPAddr, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveSegmentRegService", arg0, arg1)
	ret0, _ := ret[0].(*snet.UDPAddr)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveSegmentRegService indicates an expected call of ResolveSegmentRegService
func (mr *MockServiceResolverMockRecorder) ResolveSegmentRegService(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveSegmentRegService", reflect.TypeOf((*MockServiceResolver)(nil).ResolveSegmentRegService), arg0, arg1)
}

// ResolveTrustService mocks base method
func (m *MockServiceResolver) ResolveTrustService(arg0 context.Context, arg1 *snet.SVCAddr) (*snet.UDPAddr, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveTrustService", arg0, arg1)
	ret0, _ := ret[0].(*snet.UDPAddr)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveTrustService indicates an expected call of ResolveTrustService
func (mr *MockServiceResolverMockRecorder) ResolveTrustService(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveTrustService", reflect.TypeOf((*MockServiceResolver)(nil).ResolveTrustService), arg0, arg1)
}
