// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/scionproto/scion/go/co/reservationstore (interfaces: ServiceProvider)

// Package mock_reservationstore is a generated GoMock package.
package mock_reservationstore

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	reservation "github.com/scionproto/scion/go/co/reservation"
	segment "github.com/scionproto/scion/go/co/reservation/segment"
	addr "github.com/scionproto/scion/go/lib/addr"
	colibri "github.com/scionproto/scion/go/lib/slayers/path/colibri"
	snet "github.com/scionproto/scion/go/lib/snet"
)

// MockServiceProvider is a mock of ServiceProvider interface.
type MockServiceProvider struct {
	ctrl     *gomock.Controller
	recorder *MockServiceProviderMockRecorder
}

// MockServiceProviderMockRecorder is the mock recorder for MockServiceProvider.
type MockServiceProviderMockRecorder struct {
	mock *MockServiceProvider
}

// NewMockServiceProvider creates a new mock instance.
func NewMockServiceProvider(ctrl *gomock.Controller) *MockServiceProvider {
	mock := &MockServiceProvider{ctrl: ctrl}
	mock.recorder = &MockServiceProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceProvider) EXPECT() *MockServiceProviderMockRecorder {
	return m.recorder
}

// ActivateRequest mocks base method.
func (m *MockServiceProvider) ActivateRequest(arg0 context.Context, arg1 *reservation.Request, arg2 reservation.PathSteps, arg3 *colibri.ColibriPathMinimal, arg4 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateRequest", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// ActivateRequest indicates an expected call of ActivateRequest.
func (mr *MockServiceProviderMockRecorder) ActivateRequest(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateRequest", reflect.TypeOf((*MockServiceProvider)(nil).ActivateRequest), arg0, arg1, arg2, arg3, arg4)
}

// DeleteExpiredIndices mocks base method.
func (m *MockServiceProvider) DeleteExpiredIndices(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpiredIndices", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExpiredIndices indicates an expected call of DeleteExpiredIndices.
func (mr *MockServiceProviderMockRecorder) DeleteExpiredIndices(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpiredIndices", reflect.TypeOf((*MockServiceProvider)(nil).DeleteExpiredIndices), arg0)
}

// GetReservationsAtSource mocks base method.
func (m *MockServiceProvider) GetReservationsAtSource(arg0 context.Context) ([]*segment.Reservation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReservationsAtSource", arg0)
	ret0, _ := ret[0].([]*segment.Reservation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReservationsAtSource indicates an expected call of GetReservationsAtSource.
func (mr *MockServiceProviderMockRecorder) GetReservationsAtSource(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReservationsAtSource", reflect.TypeOf((*MockServiceProvider)(nil).GetReservationsAtSource), arg0)
}

// Now mocks base method.
func (m *MockServiceProvider) Now() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Now")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now.
func (mr *MockServiceProviderMockRecorder) Now() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Now", reflect.TypeOf((*MockServiceProvider)(nil).Now))
}

// PathsTo mocks base method.
func (m *MockServiceProvider) PathsTo(arg0 context.Context, arg1 addr.IA) ([]snet.Path, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PathsTo", arg0, arg1)
	ret0, _ := ret[0].([]snet.Path)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PathsTo indicates an expected call of PathsTo.
func (mr *MockServiceProviderMockRecorder) PathsTo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PathsTo", reflect.TypeOf((*MockServiceProvider)(nil).PathsTo), arg0, arg1)
}

// SetupRequest mocks base method.
func (m *MockServiceProvider) SetupRequest(arg0 context.Context, arg1 *segment.SetupReq) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetupRequest", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetupRequest indicates an expected call of SetupRequest.
func (mr *MockServiceProviderMockRecorder) SetupRequest(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetupRequest", reflect.TypeOf((*MockServiceProvider)(nil).SetupRequest), arg0, arg1)
}
