// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/scionproto/scion/go/lib/drkey/keystore (interfaces: DRKeyStore)

// Package mock_keystore is a generated GoMock package.
package mock_keystore

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	addr "github.com/scionproto/scion/go/lib/addr"
	drkey "github.com/scionproto/scion/go/lib/drkey"
	reflect "reflect"
)

// MockDRKeyStore is a mock of DRKeyStore interface
type MockDRKeyStore struct {
	ctrl     *gomock.Controller
	recorder *MockDRKeyStoreMockRecorder
}

// MockDRKeyStoreMockRecorder is the mock recorder for MockDRKeyStore
type MockDRKeyStoreMockRecorder struct {
	mock *MockDRKeyStore
}

// NewMockDRKeyStore creates a new mock instance
func NewMockDRKeyStore(ctrl *gomock.Controller) *MockDRKeyStore {
	mock := &MockDRKeyStore{ctrl: ctrl}
	mock.recorder = &MockDRKeyStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDRKeyStore) EXPECT() *MockDRKeyStoreMockRecorder {
	return m.recorder
}

// Close mocks base method
func (m *MockDRKeyStore) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close
func (mr *MockDRKeyStoreMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDRKeyStore)(nil).Close))
}

// GetDRKeyLvl1 mocks base method
func (m *MockDRKeyStore) GetDRKeyLvl1(arg0 context.Context, arg1 *drkey.DRKeyLvl1, arg2 uint32) (*drkey.DRKeyLvl1, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDRKeyLvl1", arg0, arg1, arg2)
	ret0, _ := ret[0].(*drkey.DRKeyLvl1)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDRKeyLvl1 indicates an expected call of GetDRKeyLvl1
func (mr *MockDRKeyStoreMockRecorder) GetDRKeyLvl1(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDRKeyLvl1", reflect.TypeOf((*MockDRKeyStore)(nil).GetDRKeyLvl1), arg0, arg1, arg2)
}

// GetDRKeyLvl2 mocks base method
func (m *MockDRKeyStore) GetDRKeyLvl2(arg0 context.Context, arg1 *drkey.DRKeyLvl2, arg2 uint32) (*drkey.DRKeyLvl2, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDRKeyLvl2", arg0, arg1, arg2)
	ret0, _ := ret[0].(*drkey.DRKeyLvl2)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDRKeyLvl2 indicates an expected call of GetDRKeyLvl2
func (mr *MockDRKeyStoreMockRecorder) GetDRKeyLvl2(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDRKeyLvl2", reflect.TypeOf((*MockDRKeyStore)(nil).GetDRKeyLvl2), arg0, arg1, arg2)
}

// GetValidL1SrcASes mocks base method
func (m *MockDRKeyStore) GetValidL1SrcASes(arg0 context.Context, arg1 uint32) ([]addr.IA, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidL1SrcASes", arg0, arg1)
	ret0, _ := ret[0].([]addr.IA)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValidL1SrcASes indicates an expected call of GetValidL1SrcASes
func (mr *MockDRKeyStoreMockRecorder) GetValidL1SrcASes(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidL1SrcASes", reflect.TypeOf((*MockDRKeyStore)(nil).GetValidL1SrcASes), arg0, arg1)
}

// InsertDRKeyLvl1 mocks base method
func (m *MockDRKeyStore) InsertDRKeyLvl1(arg0 context.Context, arg1 *drkey.DRKeyLvl1) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertDRKeyLvl1", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertDRKeyLvl1 indicates an expected call of InsertDRKeyLvl1
func (mr *MockDRKeyStoreMockRecorder) InsertDRKeyLvl1(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertDRKeyLvl1", reflect.TypeOf((*MockDRKeyStore)(nil).InsertDRKeyLvl1), arg0, arg1)
}

// InsertDRKeyLvl2 mocks base method
func (m *MockDRKeyStore) InsertDRKeyLvl2(arg0 context.Context, arg1 *drkey.DRKeyLvl2) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertDRKeyLvl2", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertDRKeyLvl2 indicates an expected call of InsertDRKeyLvl2
func (mr *MockDRKeyStoreMockRecorder) InsertDRKeyLvl2(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertDRKeyLvl2", reflect.TypeOf((*MockDRKeyStore)(nil).InsertDRKeyLvl2), arg0, arg1)
}

// RemoveOutdatedDRKeyLvl1 mocks base method
func (m *MockDRKeyStore) RemoveOutdatedDRKeyLvl1(arg0 context.Context, arg1 uint32) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveOutdatedDRKeyLvl1", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveOutdatedDRKeyLvl1 indicates an expected call of RemoveOutdatedDRKeyLvl1
func (mr *MockDRKeyStoreMockRecorder) RemoveOutdatedDRKeyLvl1(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveOutdatedDRKeyLvl1", reflect.TypeOf((*MockDRKeyStore)(nil).RemoveOutdatedDRKeyLvl1), arg0, arg1)
}

// RemoveOutdatedDRKeyLvl2 mocks base method
func (m *MockDRKeyStore) RemoveOutdatedDRKeyLvl2(arg0 context.Context, arg1 uint32) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveOutdatedDRKeyLvl2", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveOutdatedDRKeyLvl2 indicates an expected call of RemoveOutdatedDRKeyLvl2
func (mr *MockDRKeyStoreMockRecorder) RemoveOutdatedDRKeyLvl2(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveOutdatedDRKeyLvl2", reflect.TypeOf((*MockDRKeyStore)(nil).RemoveOutdatedDRKeyLvl2), arg0, arg1)
}
