// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/scionproto/scion/go/lib/drkey/keystore (interfaces: DRKeyStore)

// Package mock_keystore is a generated GoMock package.
package mock_keystore

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	addr "github.com/scionproto/scion/go/lib/addr"
	common "github.com/scionproto/scion/go/lib/common"
	drkey "github.com/scionproto/scion/go/lib/drkey"
	reflect "reflect"
	time "time"
)

// MockDRKeyStore is a mock of DRKeyStore interface
type MockDRKeyStore struct {
	ctrl     *gomock.Controller
	recorder *MockDRKeyStoreMockRecorder
}

// MockDRKeyStoreMockRecorder is the mock recorder for MockDRKeyStore
type MockDRKeyStoreMockRecorder struct {
	mock *MockDRKeyStore
}

// NewMockDRKeyStore creates a new mock instance
func NewMockDRKeyStore(ctrl *gomock.Controller) *MockDRKeyStore {
	mock := &MockDRKeyStore{ctrl: ctrl}
	mock.recorder = &MockDRKeyStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDRKeyStore) EXPECT() *MockDRKeyStoreMockRecorder {
	return m.recorder
}

// Close mocks base method
func (m *MockDRKeyStore) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close
func (mr *MockDRKeyStoreMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDRKeyStore)(nil).Close))
}

// GetDRKeyLvl1 mocks base method
func (m *MockDRKeyStore) GetDRKeyLvl1(arg0 context.Context, arg1 drkey.Lvl1Meta, arg2 uint32) (drkey.Lvl1Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDRKeyLvl1", arg0, arg1, arg2)
	ret0, _ := ret[0].(drkey.Lvl1Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDRKeyLvl1 indicates an expected call of GetDRKeyLvl1
func (mr *MockDRKeyStoreMockRecorder) GetDRKeyLvl1(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDRKeyLvl1", reflect.TypeOf((*MockDRKeyStore)(nil).GetDRKeyLvl1), arg0, arg1, arg2)
}

// GetDRKeyLvl2 mocks base method
func (m *MockDRKeyStore) GetDRKeyLvl2(arg0 context.Context, arg1 drkey.Lvl2Meta, arg2 uint32) (drkey.Lvl2Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDRKeyLvl2", arg0, arg1, arg2)
	ret0, _ := ret[0].(drkey.Lvl2Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDRKeyLvl2 indicates an expected call of GetDRKeyLvl2
func (mr *MockDRKeyStoreMockRecorder) GetDRKeyLvl2(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDRKeyLvl2", reflect.TypeOf((*MockDRKeyStore)(nil).GetDRKeyLvl2), arg0, arg1, arg2)
}

// GetKeyDuration mocks base method
func (m *MockDRKeyStore) GetKeyDuration() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeyDuration")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// GetKeyDuration indicates an expected call of GetKeyDuration
func (mr *MockDRKeyStoreMockRecorder) GetKeyDuration() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeyDuration", reflect.TypeOf((*MockDRKeyStore)(nil).GetKeyDuration))
}

// GetL1SrcASes mocks base method
func (m *MockDRKeyStore) GetL1SrcASes(arg0 context.Context) ([]addr.IA, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetL1SrcASes", arg0)
	ret0, _ := ret[0].([]addr.IA)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetL1SrcASes indicates an expected call of GetL1SrcASes
func (mr *MockDRKeyStoreMockRecorder) GetL1SrcASes(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetL1SrcASes", reflect.TypeOf((*MockDRKeyStore)(nil).GetL1SrcASes), arg0)
}

// GetMasterKey mocks base method
func (m *MockDRKeyStore) GetMasterKey() common.RawBytes {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMasterKey")
	ret0, _ := ret[0].(common.RawBytes)
	return ret0
}

// GetMasterKey indicates an expected call of GetMasterKey
func (mr *MockDRKeyStoreMockRecorder) GetMasterKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMasterKey", reflect.TypeOf((*MockDRKeyStore)(nil).GetMasterKey))
}

// GetValidL1SrcASes mocks base method
func (m *MockDRKeyStore) GetValidL1SrcASes(arg0 context.Context, arg1 uint32) ([]addr.IA, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidL1SrcASes", arg0, arg1)
	ret0, _ := ret[0].([]addr.IA)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValidL1SrcASes indicates an expected call of GetValidL1SrcASes
func (mr *MockDRKeyStoreMockRecorder) GetValidL1SrcASes(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidL1SrcASes", reflect.TypeOf((*MockDRKeyStore)(nil).GetValidL1SrcASes), arg0, arg1)
}

// InsertDRKeyLvl1 mocks base method
func (m *MockDRKeyStore) InsertDRKeyLvl1(arg0 context.Context, arg1 drkey.Lvl1Key) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertDRKeyLvl1", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertDRKeyLvl1 indicates an expected call of InsertDRKeyLvl1
func (mr *MockDRKeyStoreMockRecorder) InsertDRKeyLvl1(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertDRKeyLvl1", reflect.TypeOf((*MockDRKeyStore)(nil).InsertDRKeyLvl1), arg0, arg1)
}

// InsertDRKeyLvl2 mocks base method
func (m *MockDRKeyStore) InsertDRKeyLvl2(arg0 context.Context, arg1 drkey.Lvl2Key) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertDRKeyLvl2", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertDRKeyLvl2 indicates an expected call of InsertDRKeyLvl2
func (mr *MockDRKeyStoreMockRecorder) InsertDRKeyLvl2(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertDRKeyLvl2", reflect.TypeOf((*MockDRKeyStore)(nil).InsertDRKeyLvl2), arg0, arg1)
}

// RemoveOutdatedDRKeyLvl1 mocks base method
func (m *MockDRKeyStore) RemoveOutdatedDRKeyLvl1(arg0 context.Context, arg1 uint32) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveOutdatedDRKeyLvl1", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveOutdatedDRKeyLvl1 indicates an expected call of RemoveOutdatedDRKeyLvl1
func (mr *MockDRKeyStoreMockRecorder) RemoveOutdatedDRKeyLvl1(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveOutdatedDRKeyLvl1", reflect.TypeOf((*MockDRKeyStore)(nil).RemoveOutdatedDRKeyLvl1), arg0, arg1)
}

// RemoveOutdatedDRKeyLvl2 mocks base method
func (m *MockDRKeyStore) RemoveOutdatedDRKeyLvl2(arg0 context.Context, arg1 uint32) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveOutdatedDRKeyLvl2", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveOutdatedDRKeyLvl2 indicates an expected call of RemoveOutdatedDRKeyLvl2
func (mr *MockDRKeyStoreMockRecorder) RemoveOutdatedDRKeyLvl2(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveOutdatedDRKeyLvl2", reflect.TypeOf((*MockDRKeyStore)(nil).RemoveOutdatedDRKeyLvl2), arg0, arg1)
}

// SecretValue mocks base method
func (m *MockDRKeyStore) SecretValue(arg0 time.Time) (*drkey.SV, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SecretValue", arg0)
	ret0, _ := ret[0].(*drkey.SV)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SecretValue indicates an expected call of SecretValue
func (mr *MockDRKeyStoreMockRecorder) SecretValue(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SecretValue", reflect.TypeOf((*MockDRKeyStore)(nil).SecretValue), arg0)
}

// SetKeyDuration mocks base method
func (m *MockDRKeyStore) SetKeyDuration(arg0 time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetKeyDuration", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetKeyDuration indicates an expected call of SetKeyDuration
func (mr *MockDRKeyStoreMockRecorder) SetKeyDuration(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetKeyDuration", reflect.TypeOf((*MockDRKeyStore)(nil).SetKeyDuration), arg0)
}

// SetMasterKey mocks base method
func (m *MockDRKeyStore) SetMasterKey(arg0 common.RawBytes) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMasterKey", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMasterKey indicates an expected call of SetMasterKey
func (mr *MockDRKeyStoreMockRecorder) SetMasterKey(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMasterKey", reflect.TypeOf((*MockDRKeyStore)(nil).SetMasterKey), arg0)
}
