// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/scionproto/scion/go/pkg/discovery (interfaces: TopologyInformation)

// Package mock_discovery is a generated GoMock package.
package mock_discovery

import (
	net "net"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	topology "github.com/scionproto/scion/go/lib/topology"
)

// MockTopologyInformation is a mock of TopologyInformation interface.
type MockTopologyInformation struct {
	ctrl     *gomock.Controller
	recorder *MockTopologyInformationMockRecorder
}

// MockTopologyInformationMockRecorder is the mock recorder for MockTopologyInformation.
type MockTopologyInformationMockRecorder struct {
	mock *MockTopologyInformation
}

// NewMockTopologyInformation creates a new mock instance.
func NewMockTopologyInformation(ctrl *gomock.Controller) *MockTopologyInformation {
	mock := &MockTopologyInformation{ctrl: ctrl}
	mock.recorder = &MockTopologyInformationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTopologyInformation) EXPECT() *MockTopologyInformationMockRecorder {
	return m.recorder
}

// ChainRenewalAddress mocks base method.
func (m *MockTopologyInformation) ChainRenewalAddress() ([]*net.UDPAddr, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChainRenewalAddress")
	ret0, _ := ret[0].([]*net.UDPAddr)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChainRenewalAddress indicates an expected call of ChainRenewalAddress.
func (mr *MockTopologyInformationMockRecorder) ChainRenewalAddress() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChainRenewalAddress", reflect.TypeOf((*MockTopologyInformation)(nil).ChainRenewalAddress))
}

// ColibriServices mocks base method.
func (m *MockTopologyInformation) ColibriServices() ([]*net.UDPAddr, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ColibriServices")
	ret0, _ := ret[0].([]*net.UDPAddr)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ColibriServices indicates an expected call of ColibriServices.
func (mr *MockTopologyInformationMockRecorder) ColibriServices() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ColibriServices", reflect.TypeOf((*MockTopologyInformation)(nil).ColibriServices))
}

// DRKeyAddress mocks base method.
func (m *MockTopologyInformation) DRKeyAddress() ([]*net.UDPAddr, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DRKeyAddress")
	ret0, _ := ret[0].([]*net.UDPAddr)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DRKeyAddress indicates an expected call of DRKeyAddress.
func (mr *MockTopologyInformationMockRecorder) DRKeyAddress() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DRKeyAddress", reflect.TypeOf((*MockTopologyInformation)(nil).DRKeyAddress))
}

// Gateways mocks base method.
func (m *MockTopologyInformation) Gateways() ([]topology.GatewayInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Gateways")
	ret0, _ := ret[0].([]topology.GatewayInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Gateways indicates an expected call of Gateways.
func (mr *MockTopologyInformationMockRecorder) Gateways() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Gateways", reflect.TypeOf((*MockTopologyInformation)(nil).Gateways))
}

// HiddenSegmentLookupAddresses mocks base method.
func (m *MockTopologyInformation) HiddenSegmentLookupAddresses() ([]*net.UDPAddr, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HiddenSegmentLookupAddresses")
	ret0, _ := ret[0].([]*net.UDPAddr)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HiddenSegmentLookupAddresses indicates an expected call of HiddenSegmentLookupAddresses.
func (mr *MockTopologyInformationMockRecorder) HiddenSegmentLookupAddresses() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HiddenSegmentLookupAddresses", reflect.TypeOf((*MockTopologyInformation)(nil).HiddenSegmentLookupAddresses))
}

// HiddenSegmentRegistrationAddresses mocks base method.
func (m *MockTopologyInformation) HiddenSegmentRegistrationAddresses() ([]*net.UDPAddr, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HiddenSegmentRegistrationAddresses")
	ret0, _ := ret[0].([]*net.UDPAddr)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HiddenSegmentRegistrationAddresses indicates an expected call of HiddenSegmentRegistrationAddresses.
func (mr *MockTopologyInformationMockRecorder) HiddenSegmentRegistrationAddresses() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HiddenSegmentRegistrationAddresses", reflect.TypeOf((*MockTopologyInformation)(nil).HiddenSegmentRegistrationAddresses))
}

// SegLookupAddress mocks base method.
func (m *MockTopologyInformation) SegLookupAddress() ([]*net.UDPAddr, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SegLookupAddress")
	ret0, _ := ret[0].([]*net.UDPAddr)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SegLookupAddress indicates an expected call of SegLookupAddress.
func (mr *MockTopologyInformationMockRecorder) SegLookupAddress() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SegLookupAddress", reflect.TypeOf((*MockTopologyInformation)(nil).SegLookupAddress))
}

// SegRegAddress mocks base method.
func (m *MockTopologyInformation) SegRegAddress() ([]*net.UDPAddr, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SegRegAddress")
	ret0, _ := ret[0].([]*net.UDPAddr)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SegRegAddress indicates an expected call of SegRegAddress.
func (mr *MockTopologyInformationMockRecorder) SegRegAddress() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SegRegAddress", reflect.TypeOf((*MockTopologyInformation)(nil).SegRegAddress))
}

// TrustMaterialAddress mocks base method.
func (m *MockTopologyInformation) TrustMaterialAddress() ([]*net.UDPAddr, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrustMaterialAddress")
	ret0, _ := ret[0].([]*net.UDPAddr)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TrustMaterialAddress indicates an expected call of TrustMaterialAddress.
func (mr *MockTopologyInformationMockRecorder) TrustMaterialAddress() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrustMaterialAddress", reflect.TypeOf((*MockTopologyInformation)(nil).TrustMaterialAddress))
}
