// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/scionproto/scion/go/lib/drkey (interfaces: Lvl2DB)

// Package mock_drkey is a generated GoMock package.
package mock_drkey

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	drkey "github.com/scionproto/scion/go/lib/drkey"
)

// MockLvl2DB is a mock of Lvl2DB interface.
type MockLvl2DB struct {
	ctrl     *gomock.Controller
	recorder *MockLvl2DBMockRecorder
}

// MockLvl2DBMockRecorder is the mock recorder for MockLvl2DB.
type MockLvl2DBMockRecorder struct {
	mock *MockLvl2DB
}

// NewMockLvl2DB creates a new mock instance.
func NewMockLvl2DB(ctrl *gomock.Controller) *MockLvl2DB {
	mock := &MockLvl2DB{ctrl: ctrl}
	mock.recorder = &MockLvl2DBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLvl2DB) EXPECT() *MockLvl2DBMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockLvl2DB) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockLvl2DBMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockLvl2DB)(nil).Close))
}

// GetLvl2Key mocks base method.
func (m *MockLvl2DB) GetLvl2Key(arg0 context.Context, arg1 drkey.Lvl2Meta, arg2 uint32) (drkey.Lvl2Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLvl2Key", arg0, arg1, arg2)
	ret0, _ := ret[0].(drkey.Lvl2Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLvl2Key indicates an expected call of GetLvl2Key.
func (mr *MockLvl2DBMockRecorder) GetLvl2Key(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLvl2Key", reflect.TypeOf((*MockLvl2DB)(nil).GetLvl2Key), arg0, arg1, arg2)
}

// InsertLvl2Key mocks base method.
func (m *MockLvl2DB) InsertLvl2Key(arg0 context.Context, arg1 drkey.Lvl2Key) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertLvl2Key", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertLvl2Key indicates an expected call of InsertLvl2Key.
func (mr *MockLvl2DBMockRecorder) InsertLvl2Key(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertLvl2Key", reflect.TypeOf((*MockLvl2DB)(nil).InsertLvl2Key), arg0, arg1)
}

// RemoveOutdatedLvl2Keys mocks base method.
func (m *MockLvl2DB) RemoveOutdatedLvl2Keys(arg0 context.Context, arg1 uint32) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveOutdatedLvl2Keys", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveOutdatedLvl2Keys indicates an expected call of RemoveOutdatedLvl2Keys.
func (mr *MockLvl2DBMockRecorder) RemoveOutdatedLvl2Keys(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveOutdatedLvl2Keys", reflect.TypeOf((*MockLvl2DB)(nil).RemoveOutdatedLvl2Keys), arg0, arg1)
}

// SetMaxIdleConns mocks base method.
func (m *MockLvl2DB) SetMaxIdleConns(arg0 int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetMaxIdleConns", arg0)
}

// SetMaxIdleConns indicates an expected call of SetMaxIdleConns.
func (mr *MockLvl2DBMockRecorder) SetMaxIdleConns(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMaxIdleConns", reflect.TypeOf((*MockLvl2DB)(nil).SetMaxIdleConns), arg0)
}

// SetMaxOpenConns mocks base method.
func (m *MockLvl2DB) SetMaxOpenConns(arg0 int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetMaxOpenConns", arg0)
}

// SetMaxOpenConns indicates an expected call of SetMaxOpenConns.
func (mr *MockLvl2DBMockRecorder) SetMaxOpenConns(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMaxOpenConns", reflect.TypeOf((*MockLvl2DB)(nil).SetMaxOpenConns), arg0)
}
