// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.3
// source: proto/colibri/v1/drkey.proto

package colibri

import (
	context "context"
	control_plane "github.com/scionproto/scion/go/pkg/proto/control_plane"
	crypto "github.com/scionproto/scion/go/pkg/proto/crypto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DRKeyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chain          *control_plane.Chain  `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"`
	Segments       []*ReservationID      `protobuf:"bytes,2,rep,name=segments,proto3" json:"segments,omitempty"`
	CurrentSegment uint32                `protobuf:"varint,3,opt,name=current_segment,json=currentSegment,proto3" json:"current_segment,omitempty"`
	SignedRequest  *crypto.SignedMessage `protobuf:"bytes,4,opt,name=signed_request,json=signedRequest,proto3" json:"signed_request,omitempty"`
}

func (x *DRKeyRequest) Reset() {
	*x = DRKeyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_colibri_v1_drkey_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DRKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DRKeyRequest) ProtoMessage() {}

func (x *DRKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_colibri_v1_drkey_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DRKeyRequest.ProtoReflect.Descriptor instead.
func (*DRKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_colibri_v1_drkey_proto_rawDescGZIP(), []int{0}
}

func (x *DRKeyRequest) GetChain() *control_plane.Chain {
	if x != nil {
		return x.Chain
	}
	return nil
}

func (x *DRKeyRequest) GetSegments() []*ReservationID {
	if x != nil {
		return x.Segments
	}
	return nil
}

func (x *DRKeyRequest) GetCurrentSegment() uint32 {
	if x != nil {
		return x.CurrentSegment
	}
	return 0
}

func (x *DRKeyRequest) GetSignedRequest() *crypto.SignedMessage {
	if x != nil {
		return x.SignedRequest
	}
	return nil
}

type DRKeyRequestBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EphPubkey []byte                 `protobuf:"bytes,1,opt,name=eph_pubkey,json=ephPubkey,proto3" json:"eph_pubkey,omitempty"`
	ValTime   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=valTime,proto3" json:"valTime,omitempty"`
}

func (x *DRKeyRequestBody) Reset() {
	*x = DRKeyRequestBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_colibri_v1_drkey_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DRKeyRequestBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DRKeyRequestBody) ProtoMessage() {}

func (x *DRKeyRequestBody) ProtoReflect() protoreflect.Message {
	mi := &file_proto_colibri_v1_drkey_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DRKeyRequestBody.ProtoReflect.Descriptor instead.
func (*DRKeyRequestBody) Descriptor() ([]byte, []int) {
	return file_proto_colibri_v1_drkey_proto_rawDescGZIP(), []int{1}
}

func (x *DRKeyRequestBody) GetEphPubkey() []byte {
	if x != nil {
		return x.EphPubkey
	}
	return nil
}

func (x *DRKeyRequestBody) GetValTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ValTime
	}
	return nil
}

type DRKeyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chain          *control_plane.Chain  `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"`
	SignedResponse *crypto.SignedMessage `protobuf:"bytes,2,opt,name=signed_response,json=signedResponse,proto3" json:"signed_response,omitempty"`
}

func (x *DRKeyResponse) Reset() {
	*x = DRKeyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_colibri_v1_drkey_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DRKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DRKeyResponse) ProtoMessage() {}

func (x *DRKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_colibri_v1_drkey_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DRKeyResponse.ProtoReflect.Descriptor instead.
func (*DRKeyResponse) Descriptor() ([]byte, []int) {
	return file_proto_colibri_v1_drkey_proto_rawDescGZIP(), []int{2}
}

func (x *DRKeyResponse) GetChain() *control_plane.Chain {
	if x != nil {
		return x.Chain
	}
	return nil
}

func (x *DRKeyResponse) GetSignedResponse() *crypto.SignedMessage {
	if x != nil {
		return x.SignedResponse
	}
	return nil
}

type DRKeyResponseBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EphPubkey []byte `protobuf:"bytes,1,opt,name=eph_pubkey,json=ephPubkey,proto3" json:"eph_pubkey,omitempty"`
	Nonce     []byte `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Cipher    []byte `protobuf:"bytes,3,opt,name=cipher,proto3" json:"cipher,omitempty"`
}

func (x *DRKeyResponseBody) Reset() {
	*x = DRKeyResponseBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_colibri_v1_drkey_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DRKeyResponseBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DRKeyResponseBody) ProtoMessage() {}

func (x *DRKeyResponseBody) ProtoReflect() protoreflect.Message {
	mi := &file_proto_colibri_v1_drkey_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DRKeyResponseBody.ProtoReflect.Descriptor instead.
func (*DRKeyResponseBody) Descriptor() ([]byte, []int) {
	return file_proto_colibri_v1_drkey_proto_rawDescGZIP(), []int{3}
}

func (x *DRKeyResponseBody) GetEphPubkey() []byte {
	if x != nil {
		return x.EphPubkey
	}
	return nil
}

func (x *DRKeyResponseBody) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *DRKeyResponseBody) GetCipher() []byte {
	if x != nil {
		return x.Cipher
	}
	return nil
}

type ASHostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EpochBegin *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=epoch_begin,json=epochBegin,proto3" json:"epoch_begin,omitempty"`
	EpochEnd   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=epoch_end,json=epochEnd,proto3" json:"epoch_end,omitempty"`
	Key        []byte                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *ASHostResponse) Reset() {
	*x = ASHostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_colibri_v1_drkey_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ASHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ASHostResponse) ProtoMessage() {}

func (x *ASHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_colibri_v1_drkey_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ASHostResponse.ProtoReflect.Descriptor instead.
func (*ASHostResponse) Descriptor() ([]byte, []int) {
	return file_proto_colibri_v1_drkey_proto_rawDescGZIP(), []int{4}
}

func (x *ASHostResponse) GetEpochBegin() *timestamppb.Timestamp {
	if x != nil {
		return x.EpochBegin
	}
	return nil
}

func (x *ASHostResponse) GetEpochEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.EpochEnd
	}
	return nil
}

func (x *ASHostResponse) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

var File_proto_colibri_v1_drkey_proto protoreflect.FileDescriptor

var file_proto_colibri_v1_drkey_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6c, 0x69, 0x62, 0x72, 0x69, 0x2f,
	0x76, 0x31, 0x2f, 0x64, 0x72, 0x6b, 0x65, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6c, 0x69, 0x62, 0x72, 0x69, 0x2e, 0x76, 0x31,
	0x1a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6c, 0x69, 0x62, 0x72, 0x69, 0x2f,
	0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6c, 0x69, 0x62, 0x72, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x2f, 0x76,
	0x31, 0x2f, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x22,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x70, 0x6c,
	0x61, 0x6e, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x70, 0x70, 0x6b, 0x69, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xf0, 0x01, 0x0a, 0x0c, 0x44, 0x52, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x05, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x6f, 0x6c, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x61,
	0x69, 0x6e, 0x52, 0x05, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x3b, 0x0a, 0x08, 0x73, 0x65, 0x67,
	0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6c, 0x69, 0x62, 0x72, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x52, 0x08, 0x73, 0x65,
	0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x74, 0x5f, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0e, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x12,
	0x45, 0x0a, 0x0e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x0d, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x67, 0x0a, 0x10, 0x44, 0x52, 0x4b, 0x65, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x70,
	0x68, 0x5f, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09,
	0x65, 0x70, 0x68, 0x50, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x12, 0x34, 0x0a, 0x07, 0x76, 0x61, 0x6c,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x76, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x22,
	0x8d, 0x01, 0x0a, 0x0d, 0x44, 0x52, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x33, 0x0a, 0x05, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x52,
	0x05, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x47, 0x0a, 0x0f, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64,
	0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52,
	0x0e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x60, 0x0a, 0x11, 0x44, 0x52, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x6f, 0x64, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x70, 0x68, 0x5f, 0x70, 0x75, 0x62, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x65, 0x70, 0x68, 0x50, 0x75, 0x62,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x69, 0x70,
	0x68, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x63, 0x69, 0x70, 0x68, 0x65,
	0x72, 0x22, 0x98, 0x01, 0x0a, 0x0e, 0x41, 0x53, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0b, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x5f, 0x62, 0x65,
	0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x42, 0x65, 0x67, 0x69,
	0x6e, 0x12, 0x37, 0x0a, 0x09, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x5f, 0x65, 0x6e, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x08, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x45, 0x6e, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x32, 0x53, 0x0a, 0x05,
	0x44, 0x52, 0x4b, 0x65, 0x79, 0x12, 0x4a, 0x0a, 0x05, 0x44, 0x52, 0x4b, 0x65, 0x79, 0x12, 0x1e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6c, 0x69, 0x62, 0x72, 0x69, 0x2e, 0x76,
	0x31, 0x2e, 0x44, 0x52, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6c, 0x69, 0x62, 0x72, 0x69, 0x2e, 0x76,
	0x31, 0x2e, 0x44, 0x52, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x73, 0x63, 0x69, 0x6f, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x63, 0x69, 0x6f, 0x6e,
	0x2f, 0x67, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f,
	0x6c, 0x69, 0x62, 0x72, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_colibri_v1_drkey_proto_rawDescOnce sync.Once
	file_proto_colibri_v1_drkey_proto_rawDescData = file_proto_colibri_v1_drkey_proto_rawDesc
)

func file_proto_colibri_v1_drkey_proto_rawDescGZIP() []byte {
	file_proto_colibri_v1_drkey_proto_rawDescOnce.Do(func() {
		file_proto_colibri_v1_drkey_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_colibri_v1_drkey_proto_rawDescData)
	})
	return file_proto_colibri_v1_drkey_proto_rawDescData
}

var file_proto_colibri_v1_drkey_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_colibri_v1_drkey_proto_goTypes = []interface{}{
	(*DRKeyRequest)(nil),          // 0: proto.colibri.v1.DRKeyRequest
	(*DRKeyRequestBody)(nil),      // 1: proto.colibri.v1.DRKeyRequestBody
	(*DRKeyResponse)(nil),         // 2: proto.colibri.v1.DRKeyResponse
	(*DRKeyResponseBody)(nil),     // 3: proto.colibri.v1.DRKeyResponseBody
	(*ASHostResponse)(nil),        // 4: proto.colibri.v1.ASHostResponse
	(*control_plane.Chain)(nil),   // 5: proto.control_plane.v1.Chain
	(*ReservationID)(nil),         // 6: proto.colibri.v1.ReservationID
	(*crypto.SignedMessage)(nil),  // 7: proto.crypto.v1.SignedMessage
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_proto_colibri_v1_drkey_proto_depIdxs = []int32{
	5, // 0: proto.colibri.v1.DRKeyRequest.chain:type_name -> proto.control_plane.v1.Chain
	6, // 1: proto.colibri.v1.DRKeyRequest.segments:type_name -> proto.colibri.v1.ReservationID
	7, // 2: proto.colibri.v1.DRKeyRequest.signed_request:type_name -> proto.crypto.v1.SignedMessage
	8, // 3: proto.colibri.v1.DRKeyRequestBody.valTime:type_name -> google.protobuf.Timestamp
	5, // 4: proto.colibri.v1.DRKeyResponse.chain:type_name -> proto.control_plane.v1.Chain
	7, // 5: proto.colibri.v1.DRKeyResponse.signed_response:type_name -> proto.crypto.v1.SignedMessage
	8, // 6: proto.colibri.v1.ASHostResponse.epoch_begin:type_name -> google.protobuf.Timestamp
	8, // 7: proto.colibri.v1.ASHostResponse.epoch_end:type_name -> google.protobuf.Timestamp
	0, // 8: proto.colibri.v1.DRKey.DRKey:input_type -> proto.colibri.v1.DRKeyRequest
	2, // 9: proto.colibri.v1.DRKey.DRKey:output_type -> proto.colibri.v1.DRKeyResponse
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_proto_colibri_v1_drkey_proto_init() }
func file_proto_colibri_v1_drkey_proto_init() {
	if File_proto_colibri_v1_drkey_proto != nil {
		return
	}
	file_proto_colibri_v1_colibri_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_colibri_v1_drkey_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DRKeyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_colibri_v1_drkey_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DRKeyRequestBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_colibri_v1_drkey_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DRKeyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_colibri_v1_drkey_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DRKeyResponseBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_colibri_v1_drkey_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ASHostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_colibri_v1_drkey_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_colibri_v1_drkey_proto_goTypes,
		DependencyIndexes: file_proto_colibri_v1_drkey_proto_depIdxs,
		MessageInfos:      file_proto_colibri_v1_drkey_proto_msgTypes,
	}.Build()
	File_proto_colibri_v1_drkey_proto = out.File
	file_proto_colibri_v1_drkey_proto_rawDesc = nil
	file_proto_colibri_v1_drkey_proto_goTypes = nil
	file_proto_colibri_v1_drkey_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DRKeyClient is the client API for DRKey service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DRKeyClient interface {
	DRKey(ctx context.Context, in *DRKeyRequest, opts ...grpc.CallOption) (*DRKeyResponse, error)
}

type dRKeyClient struct {
	cc grpc.ClientConnInterface
}

func NewDRKeyClient(cc grpc.ClientConnInterface) DRKeyClient {
	return &dRKeyClient{cc}
}

func (c *dRKeyClient) DRKey(ctx context.Context, in *DRKeyRequest, opts ...grpc.CallOption) (*DRKeyResponse, error) {
	out := new(DRKeyResponse)
	err := c.cc.Invoke(ctx, "/proto.colibri.v1.DRKey/DRKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DRKeyServer is the server API for DRKey service.
type DRKeyServer interface {
	DRKey(context.Context, *DRKeyRequest) (*DRKeyResponse, error)
}

// UnimplementedDRKeyServer can be embedded to have forward compatible implementations.
type UnimplementedDRKeyServer struct {
}

func (*UnimplementedDRKeyServer) DRKey(context.Context, *DRKeyRequest) (*DRKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DRKey not implemented")
}

func RegisterDRKeyServer(s *grpc.Server, srv DRKeyServer) {
	s.RegisterService(&_DRKey_serviceDesc, srv)
}

func _DRKey_DRKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DRKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DRKeyServer).DRKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.colibri.v1.DRKey/DRKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DRKeyServer).DRKey(ctx, req.(*DRKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DRKey_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.colibri.v1.DRKey",
	HandlerType: (*DRKeyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DRKey",
			Handler:    _DRKey_DRKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/colibri/v1/drkey.proto",
}
