// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/scionproto/scion/go/lib/drkeystorage (interfaces: Store)

// Package mock_drkeystorage is a generated GoMock package.
package mock_drkeystorage

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	addr "github.com/scionproto/scion/go/lib/addr"
	common "github.com/scionproto/scion/go/lib/common"
	drkey "github.com/scionproto/scion/go/lib/drkey"
	reflect "reflect"
	time "time"
)

// MockStore is a mock of Store interface
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// GetKeyDuration mocks base method
func (m *MockStore) GetKeyDuration() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeyDuration")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// GetKeyDuration indicates an expected call of GetKeyDuration
func (mr *MockStoreMockRecorder) GetKeyDuration() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeyDuration", reflect.TypeOf((*MockStore)(nil).GetKeyDuration))
}

// GetLvl1Key mocks base method
func (m *MockStore) GetLvl1Key(arg0 context.Context, arg1 drkey.Lvl1Meta, arg2 uint32) (drkey.Lvl1Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLvl1Key", arg0, arg1, arg2)
	ret0, _ := ret[0].(drkey.Lvl1Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLvl1Key indicates an expected call of GetLvl1Key
func (mr *MockStoreMockRecorder) GetLvl1Key(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLvl1Key", reflect.TypeOf((*MockStore)(nil).GetLvl1Key), arg0, arg1, arg2)
}

// GetLvl1SrcASes mocks base method
func (m *MockStore) GetLvl1SrcASes(arg0 context.Context) ([]addr.IA, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLvl1SrcASes", arg0)
	ret0, _ := ret[0].([]addr.IA)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLvl1SrcASes indicates an expected call of GetLvl1SrcASes
func (mr *MockStoreMockRecorder) GetLvl1SrcASes(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLvl1SrcASes", reflect.TypeOf((*MockStore)(nil).GetLvl1SrcASes), arg0)
}

// GetLvl2Key mocks base method
func (m *MockStore) GetLvl2Key(arg0 context.Context, arg1 drkey.Lvl2Meta, arg2 uint32) (drkey.Lvl2Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLvl2Key", arg0, arg1, arg2)
	ret0, _ := ret[0].(drkey.Lvl2Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLvl2Key indicates an expected call of GetLvl2Key
func (mr *MockStoreMockRecorder) GetLvl2Key(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLvl2Key", reflect.TypeOf((*MockStore)(nil).GetLvl2Key), arg0, arg1, arg2)
}

// GetMasterKey mocks base method
func (m *MockStore) GetMasterKey() common.RawBytes {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMasterKey")
	ret0, _ := ret[0].(common.RawBytes)
	return ret0
}

// GetMasterKey indicates an expected call of GetMasterKey
func (mr *MockStoreMockRecorder) GetMasterKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMasterKey", reflect.TypeOf((*MockStore)(nil).GetMasterKey))
}

// GetValidLvl1SrcASes mocks base method
func (m *MockStore) GetValidLvl1SrcASes(arg0 context.Context, arg1 uint32) ([]addr.IA, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidLvl1SrcASes", arg0, arg1)
	ret0, _ := ret[0].([]addr.IA)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValidLvl1SrcASes indicates an expected call of GetValidLvl1SrcASes
func (mr *MockStoreMockRecorder) GetValidLvl1SrcASes(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidLvl1SrcASes", reflect.TypeOf((*MockStore)(nil).GetValidLvl1SrcASes), arg0, arg1)
}

// InsertLvl1Key mocks base method
func (m *MockStore) InsertLvl1Key(arg0 context.Context, arg1 drkey.Lvl1Key) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertLvl1Key", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertLvl1Key indicates an expected call of InsertLvl1Key
func (mr *MockStoreMockRecorder) InsertLvl1Key(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertLvl1Key", reflect.TypeOf((*MockStore)(nil).InsertLvl1Key), arg0, arg1)
}

// InsertLvl2Key mocks base method
func (m *MockStore) InsertLvl2Key(arg0 context.Context, arg1 drkey.Lvl2Key) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertLvl2Key", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertLvl2Key indicates an expected call of InsertLvl2Key
func (mr *MockStoreMockRecorder) InsertLvl2Key(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertLvl2Key", reflect.TypeOf((*MockStore)(nil).InsertLvl2Key), arg0, arg1)
}

// RemoveOutdatedLvl1Keys mocks base method
func (m *MockStore) RemoveOutdatedLvl1Keys(arg0 context.Context, arg1 uint32) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveOutdatedLvl1Keys", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveOutdatedLvl1Keys indicates an expected call of RemoveOutdatedLvl1Keys
func (mr *MockStoreMockRecorder) RemoveOutdatedLvl1Keys(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveOutdatedLvl1Keys", reflect.TypeOf((*MockStore)(nil).RemoveOutdatedLvl1Keys), arg0, arg1)
}

// RemoveOutdatedLvl2Keys mocks base method
func (m *MockStore) RemoveOutdatedLvl2Keys(arg0 context.Context, arg1 uint32) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveOutdatedLvl2Keys", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveOutdatedLvl2Keys indicates an expected call of RemoveOutdatedLvl2Keys
func (mr *MockStoreMockRecorder) RemoveOutdatedLvl2Keys(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveOutdatedLvl2Keys", reflect.TypeOf((*MockStore)(nil).RemoveOutdatedLvl2Keys), arg0, arg1)
}

// SecretValue mocks base method
func (m *MockStore) SecretValue(arg0 time.Time) (*drkey.SV, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SecretValue", arg0)
	ret0, _ := ret[0].(*drkey.SV)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SecretValue indicates an expected call of SecretValue
func (mr *MockStoreMockRecorder) SecretValue(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SecretValue", reflect.TypeOf((*MockStore)(nil).SecretValue), arg0)
}

// SetKeyDuration mocks base method
func (m *MockStore) SetKeyDuration(arg0 time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetKeyDuration", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetKeyDuration indicates an expected call of SetKeyDuration
func (mr *MockStoreMockRecorder) SetKeyDuration(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetKeyDuration", reflect.TypeOf((*MockStore)(nil).SetKeyDuration), arg0)
}

// SetMasterKey mocks base method
func (m *MockStore) SetMasterKey(arg0 common.RawBytes) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMasterKey", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMasterKey indicates an expected call of SetMasterKey
func (mr *MockStoreMockRecorder) SetMasterKey(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMasterKey", reflect.TypeOf((*MockStore)(nil).SetMasterKey), arg0)
}
