// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/scionproto/scion/go/lib/drkeystorage (interfaces: ServiceStore)

// Package mock_drkeystorage is a generated GoMock package.
package mock_drkeystorage

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	drkey "github.com/scionproto/scion/go/lib/drkey"
	protocol "github.com/scionproto/scion/go/lib/drkey/protocol"
	infra "github.com/scionproto/scion/go/lib/infra"
	reflect "reflect"
	time "time"
)

// MockServiceStore is a mock of ServiceStore interface
type MockServiceStore struct {
	ctrl     *gomock.Controller
	recorder *MockServiceStoreMockRecorder
}

// MockServiceStoreMockRecorder is the mock recorder for MockServiceStore
type MockServiceStoreMockRecorder struct {
	mock *MockServiceStore
}

// NewMockServiceStore creates a new mock instance
func NewMockServiceStore(ctrl *gomock.Controller) *MockServiceStore {
	mock := &MockServiceStore{ctrl: ctrl}
	mock.recorder = &MockServiceStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockServiceStore) EXPECT() *MockServiceStoreMockRecorder {
	return m.recorder
}

// DeleteExpiredKeys mocks base method
func (m *MockServiceStore) DeleteExpiredKeys(arg0 context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpiredKeys", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExpiredKeys indicates an expected call of DeleteExpiredKeys
func (mr *MockServiceStoreMockRecorder) DeleteExpiredKeys(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpiredKeys", reflect.TypeOf((*MockServiceStore)(nil).DeleteExpiredKeys), arg0)
}

// GetLvl1Key mocks base method
func (m *MockServiceStore) GetLvl1Key(arg0 context.Context, arg1 drkey.Lvl1Meta, arg2 time.Time) (drkey.Lvl1Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLvl1Key", arg0, arg1, arg2)
	ret0, _ := ret[0].(drkey.Lvl1Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLvl1Key indicates an expected call of GetLvl1Key
func (mr *MockServiceStoreMockRecorder) GetLvl1Key(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLvl1Key", reflect.TypeOf((*MockServiceStore)(nil).GetLvl1Key), arg0, arg1, arg2)
}

// NewLvl1ReqHandler mocks base method
func (m *MockServiceStore) NewLvl1ReqHandler() infra.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewLvl1ReqHandler")
	ret0, _ := ret[0].(infra.Handler)
	return ret0
}

// NewLvl1ReqHandler indicates an expected call of NewLvl1ReqHandler
func (mr *MockServiceStoreMockRecorder) NewLvl1ReqHandler() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewLvl1ReqHandler", reflect.TypeOf((*MockServiceStore)(nil).NewLvl1ReqHandler))
}

// NewLvl2ReqHandler mocks base method
func (m *MockServiceStore) NewLvl2ReqHandler(arg0 protocol.Registry) infra.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewLvl2ReqHandler", arg0)
	ret0, _ := ret[0].(infra.Handler)
	return ret0
}

// NewLvl2ReqHandler indicates an expected call of NewLvl2ReqHandler
func (mr *MockServiceStoreMockRecorder) NewLvl2ReqHandler(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewLvl2ReqHandler", reflect.TypeOf((*MockServiceStore)(nil).NewLvl2ReqHandler), arg0)
}

// SetMessenger mocks base method
func (m *MockServiceStore) SetMessenger(arg0 infra.Messenger) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetMessenger", arg0)
}

// SetMessenger indicates an expected call of SetMessenger
func (mr *MockServiceStoreMockRecorder) SetMessenger(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMessenger", reflect.TypeOf((*MockServiceStore)(nil).SetMessenger), arg0)
}
