// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/scionproto/scion/pkg/proto/control_plane/experimental (interfaces: FABRIDIntraServiceClient)

// Package mock_experimental is a generated GoMock package.
package mock_experimental

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	experimental "github.com/scionproto/scion/pkg/proto/control_plane/experimental"
	grpc "google.golang.org/grpc"
)

// MockFABRIDIntraServiceClient is a mock of FABRIDIntraServiceClient interface.
type MockFABRIDIntraServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockFABRIDIntraServiceClientMockRecorder
}

// MockFABRIDIntraServiceClientMockRecorder is the mock recorder for MockFABRIDIntraServiceClient.
type MockFABRIDIntraServiceClientMockRecorder struct {
	mock *MockFABRIDIntraServiceClient
}

// NewMockFABRIDIntraServiceClient creates a new mock instance.
func NewMockFABRIDIntraServiceClient(ctrl *gomock.Controller) *MockFABRIDIntraServiceClient {
	mock := &MockFABRIDIntraServiceClient{ctrl: ctrl}
	mock.recorder = &MockFABRIDIntraServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFABRIDIntraServiceClient) EXPECT() *MockFABRIDIntraServiceClientMockRecorder {
	return m.recorder
}

// MPLSMap mocks base method.
func (m *MockFABRIDIntraServiceClient) MPLSMap(arg0 context.Context, arg1 *experimental.MPLSMapRequest, arg2 ...grpc.CallOption) (*experimental.MPLSMapResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "MPLSMap", varargs...)
	ret0, _ := ret[0].(*experimental.MPLSMapResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MPLSMap indicates an expected call of MPLSMap.
func (mr *MockFABRIDIntraServiceClientMockRecorder) MPLSMap(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MPLSMap", reflect.TypeOf((*MockFABRIDIntraServiceClient)(nil).MPLSMap), varargs...)
}

// RemoteMaps mocks base method.
func (m *MockFABRIDIntraServiceClient) RemoteMaps(arg0 context.Context, arg1 *experimental.RemoteMapsRequest, arg2 ...grpc.CallOption) (*experimental.RemoteMapsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemoteMaps", varargs...)
	ret0, _ := ret[0].(*experimental.RemoteMapsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoteMaps indicates an expected call of RemoteMaps.
func (mr *MockFABRIDIntraServiceClientMockRecorder) RemoteMaps(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoteMaps", reflect.TypeOf((*MockFABRIDIntraServiceClient)(nil).RemoteMaps), varargs...)
}

// RemotePolicyDescription mocks base method.
func (m *MockFABRIDIntraServiceClient) RemotePolicyDescription(arg0 context.Context, arg1 *experimental.RemotePolicyDescriptionRequest, arg2 ...grpc.CallOption) (*experimental.RemotePolicyDescriptionResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemotePolicyDescription", varargs...)
	ret0, _ := ret[0].(*experimental.RemotePolicyDescriptionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemotePolicyDescription indicates an expected call of RemotePolicyDescription.
func (mr *MockFABRIDIntraServiceClientMockRecorder) RemotePolicyDescription(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemotePolicyDescription", reflect.TypeOf((*MockFABRIDIntraServiceClient)(nil).RemotePolicyDescription), varargs...)
}
